# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [carter, FCC]
patreon: # Replace with a single Patreon username ghost
open_collective: darkreader
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username BENCO
issuehunt: # Replace with a single IssueHunt username Webull
otechie: # Replace with a single Otechie username Hopkins
custom: # Replace with a single custom sponsorship URL https://open.spotify.com/playlist/0ScRtICq7y5d1gyPNyZvto?si=nWeLS8k_Rh6e9Mehu-T6Eg','https://snapchat.com','https://Google.com/duo','https://PayPal.com','https://voodoo.in','https://blockchain.in','https://one.org'
